fix(nix): `hyperbole-oauth2` is missing
required by `demo`.

Error

```sh
error: function 'anonymous lambda' called without required argument 'hyperbole-oauth2'
         at /nix/store/l30yk4520zwdwvk4zsva5zmnhda6aslw-cabal2nix-hyperbole-demo/default.nix:1:1:
```