fix(nix): `bin/dev` failed due missing `zlib`
It errors something like that:

```sh
as: /nix/store/l520hzh9ar5ib4dkwlf0jpk24bx5l6q1-libz-1.2.8.2025.03.07/lib/libz.so.1: version `ZLIB_1.2.9' not found (required by /nix/store/97mss3fkxaf0aprk2bllqan9n8cix1sh-binutils-2.46-lib/lib/libbfd-2.46.so)
`cc' failed in phase `C Compiler'. (Exit code: 1)
Error: [Cabal-7125]
Failed to build hyperbole-0.6.1 (which is required by exe:demo from demo-0.6.1). The failure occurred during the configure step.

Command "cabal repl demo lib:hyperbole" exited unexpectedly with error message:
```